### PR TITLE
Moved package information to __about__.py to avoid dependency issues

### LINKED ISSUE #133: setup.py imports firebase_admin which requires six
### [REQUIRED] Step 2: Describe your environment

  * Operating System version: MacOS 10.13
  * Firebase SDK version: 2.9.0
  * Library version: 2.9.0
  * Firebase Product: any

### [REQUIRED] Step 3: Describe the problem

If you don't already have python six installed, you can't install firebase

#### Steps to reproduce:

pip install .

#### Relevant Code:

setup.py has: `import firebase_admin` and `firebase_admin.__init__.py` has `import six` so if it isn't installed before installing the installation fails with:
```
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/rh/fs2krkgj1hz_2ftgxgl20d980000gn/T/pip-mpnc1wob-build/setup.py", line 24, in <module>
        import firebase_admin
      File "/private/var/folders/rh/fs2krkgj1hz_2ftgxgl20d980000gn/T/pip-mpnc1wob-build/firebase_admin/__init__.py", line 21, in <module>
        import six
    ModuleNotFoundError: No module named 'six'
```

### PR DESCRIPTION
**Pull request by carsongee**
This resolves #133 [warehouse](https://github.com/pypa/warehouse/blob/master/warehouse/__about__.py) style.

Happy to add more or remove more from `__about__.py`, just picked out what seemed like the obvious ones.

### CODE REVIEW

**Comment by hiranya911** [comment]
This looks solid. Thanks @carsongee for the PR.

**Comment by hiranya911** [comment]
@avishalom please check if we can include this in the next release.

File: scripts/prepare_release.sh [hunk 1]
```diff
@@ -55,9 +55,9 @@ if ! parseVersion "$VERSION"; then
     exit 1
 fi
 
-CUR_VERSION=$(grep "^__version__ =" ../firebase_admin/__init__.py | awk '{print $3}' | sed "s/'//g")
+CUR_VERSION=$(grep "^__version__ =" ../firebase_admin/__about__.py | awk '{print $3}' | sed "s/'//g")
 if [ -z "$CUR_VERSION" ]; then
-    echo "[ERROR] Failed to find the current version. Check firebase_admin/__init__.py for version declaration."
+    echo "[ERROR] Failed to find the current version. Check firebase_admin/__version__.py for version declaration."
```
Comment (avishalom) [inline scripts/prepare_release.sh]: s/__version__.py/__about__.py/ ?
